# Generated by Django 4.2.21 on 2025-05-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
